# Site settings
title: Instrodução ao Chi Kung
tag_text: Curso de Introdução ao Chi Kung
description: Solo is a Jekyll theme

# jekyll setings
source:      .
destination: ./_site

# Build settings
markdown: kramdown
exclude: ["README.md"]